name: tradebot

on: 
  schedule:
    - cron:  '15 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout repo content to github runner

      - name: set up python
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-verson: "3.7"
          activate-environment: venv

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: install python packages
        run: |
          conda install conda-forge::ta-lib
          pip install -r requirements.txt
      
      - name: run-bot
        run: python main.py
