name: tradebot

on: 
  schedule:
    -cron:  '15 9 * * *'
  workflow_dispatch:

jobs:
  trade-bot:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: pip install -r requirements.txt
      
      - name: run-bot
        run: python3 main.py
